### ISSUE TITLE
demo跑起来报错啊

### ISSUE THREAD

**Issue by qq157788394** [kaola-fed/megalo-demo#1]

**Comment by lczc** [comment]
我刚刚尝试了 npm install还是报错

**Comment by elcarim5efil** [comment]
@lczc 
npm install 报错了？能提供报错信息吗？我刚试了试没有问题的。

**Comment by Lionad-Morotar** [comment]
![code - insiders_2018-11-14_17-47-32](https://user-images.githubusercontent.com/26913795/48474457-94abd500-e835-11e8-8340-96ec5ea6c51b.png)

**Comment by Lionad-Morotar** [comment]
这是刚npminstall后打包报错
* 2018年11月14日 
* npm 5.6.0
* nodejs v8.10.0
* window 10

**Comment by Lionad-Morotar** [comment]
* npm run dev:alipay ✅
* npm run dev:wechat ✅
* npm run dev:swan ❎

**Comment by elcarim5efil** [comment]
@Lionad-Morotar 
可以看看下载的 @megalo/target 的版本是多少吗？
