### ISSUE TITLE
有生产环境脚本么?

### ISSUE THREAD

**Issue by luanwulin** [kaola-fed/megalo-demo#6]
生产和开发是一套webpack脚本，，导致生成出来的文件很大，可以优化一下么

**Comment by elcarim5efil** [comment]
生产环境切换成 production 模式基本就可以了

**Comment by luanwulin** [comment]
@elcarim5efil 不行呢，mode修改成production，dist-wechat包压缩了发给测试还是有1.2m左右，同样的代码mpvue压缩了只有800k左右。要是没压缩上传的话，刚刚好过2048kb的线

**Comment by bigmeow** [comment]
@luanwulin 这个问题好解决，你先把生成的目录删除掉,在重新生成一遍就行了
如果你之前使用的是```npm run dev:wechat``` , 再换成 production 模式再执行一遍，没用的，dev模式生成的代码还在那里 ，所以你要先清除
后面这个megalo-cli会改掉这个问题，编译生产前先清空下目录就没问题了

**Comment by luanwulin** [comment]
@bigmeow 恩啊，这些方法都尝试过的。还是比较大，后来我自己加了```minimizer```，又搞了搞```cacheGroups```好点了

**Comment by bigmeow** [comment]
@bigmeow 你可以试一下我pullrequest的那个版本，上面我说的问题解决了
其实还有优化的空间： 比如css还没压缩，模版代码去空格等等

**Comment by luanwulin** [comment]
@bigmeow 是megalo-demo项目的pr么？css压缩我已经搞定了，UglifyJs也加了。刚才又把url-loader和image-webpack-loader加上了，暂时没问题了，就看以后需求了😂

**Comment by auven** [comment]
生产化脚本打包后，分包的 `js` 被打包进主包里面了。如下
![251545574186_ pic_hd](https://user-images.githubusercontent.com/23731087/50384455-bc793d00-06ff-11e9-9e36-06dc7ff7265c.jpg)

**Comment by elcarim5efil** [comment]
`output.chunkFilename: 'static/js/[id].js'` 改成 `output.chunkFilename: 'static/js/[name].js'`
