### ISSUE TITLE
急急急! demo的支付宝小程序在ios上白屏

### ISSUE THREAD

**Issue by zhj296409022** [kaola-fed/megalo-demo#9]
"[WORKER] onerror ["TypeError: c.createElement is not a function.(In 'c.createElement(\"script\")','c.createElement' is undefined)","",0,0,{}]"

**Comment by xiexieni1992** [comment]
[WORKER] onerror ["TypeError: f.createElement is not a function. (In 'f.createElement(\"script\")', 'f.createElement' is undefined)","",0,0,{}]这个问题你是怎么解决的呢
